openapi: 3.0.3
info:
  title: Schema dell'Esito Definizione
  version: 202211.10.00
  x-summary: Schema dell'esito di definizione di un evento lesivo compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Bruno Marino
    email: b.marino@almawave.it
   # url:
  description: |-
   Esito che caratterizza la definizione ovvero la situazione amministrativa del caso di infortunio o malattia professionale.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    IdEsitoDefinizione:
      type: string
      maxLength: 20
      description: Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        Associato a https://w3id.org/italia/onto/WorkAccident/codiceEsitoDefinizione.
      example: 'CO'

    EsitoDefinizione:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/WorkAccident/EsitoDefinizione
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/WorkAccident/"
        codice_esito_definizione: codiceEsitoDefinizione
        descrizione_esito_definizione: descrizioneEsitoDefinizione
        codice_classificazione_esito_definizione: codiceClassificazioneEsitoDefinizione
        descrizione_classificazione_esito_definizione: descrizioneClassificazioneEsitoDefinizione
      additionalProperties: true
      description:
          Questo schema rappresenta l'esito definizione ed è associato a https://w3id.org/italia/onto/WorkAccident/EsitoDefinizione.
      required:
      - codice_esito_definizione
      - descrizione_esito_definizione
      - codice_classificazione_esito_definizione
      - descrizione_classificazione_esito_definizione
      properties:
        codice_esito_definizione:
          $ref: "#/components/schemas/IdEsitoDefinizione"
        descrizione_esito_definizione:
          type: string
          maxLength: 255
        codice_classificazione_esito_definizione:
          type: string
          maxLength: 20
        descrizione_classificazione_esito_definizione:
          type: string
          maxLength: 255
      example:
        codice_esito_definizione: 'CO'
        descrizione_esito_definizione: 'Comunicazione istruttoria'
        codice_classificazione_esito_definizione: 'I'
        descrizione_classificazione_esito_definizione: 'Istruttoria'