openapi: 3.0.3
info:
  title: Schema della Prestazione Economica
  version: 202211.10.00
  x-summary: Schema della prestazione economica compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Bruno Marino
    email: b.marino@almawave.it
   # url:
  description: |-
   L'Inail tutela i lavoratori che subiscono un infortunio sul lavoro o contraggono una malattia professionale (tecnopatici) o, in caso di morte, i loro superstiti mediante l'erogazione di prestazioni economiche finalizzate a indennizzare il danno derivante dall'evento lesivo.
   Le prestazioni economiche spettano, di norma, anche se il datore di lavoro non ha versato regolarmente il premio assicurativo.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    MalattiaProfessionale:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/tree/main/assets/schemas/malattia-professionale/malattia-professionale.oas3.yaml#/components/schemas/MalattiaProfessionale"
    Infortunio:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/tree/main/assets/schemas/infortunio/infortunio.oas3.yaml#/components/schemas/Infortunio"

    IdPrestazioneEconomica:
      type: integer
      format: int64
      description:
          Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
          Associato a https://w3id.org/italia/onto/WorkAccident/PrestazioneEconomica.
      example: 001234567

    PrestazioneEconomica:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/WorkAccident/PrestazioneEconomica
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/WorkAccident/"
        id_prestazione: idPrestazioneEconomica
        importo_prestazione: importoPrestazione
        prestazione_relativa_a_mp:
          "@id": prestazioneRelativaAEvento
        prestazione_relativa_a_inf:
          "@id": prestazioneRelativaAEvento
      additionalProperties: true
      description:
           Questo schema rappresenta una prestazione economica ed è associato a https://w3id.org/italia/onto/WorkAccident/PrestazioneEconomica.
      required:
      - id_prestazione
      - importo_prestazione
      properties:
        id_prestazione:
          $ref: "#/components/schemas/IdPrestazioneEconomica"
        importo_prestazione:
          type: number
          format: double
        prestazione_relativa_a_mp:
          type: object
          items:
            $ref: "#/components/schemas/MalattiaProfessionale"
        prestazione_relativa_a_inf:
          type: object
          items:
            $ref: "#/components/schemas/Infortunio"
      example:
        id_prestazione: 001234567
        importo_prestazione: 377.01
        prestazione_relativa_a_mp:
          - $ref: "#/components/schemas/MalattiaProfessionale/example"
        prestazione_relativa_a_inf:
          - $ref: "#/components/schemas/Infortunio/example"