openapi: 3.0.3
info:
  title: Schema dell'infortunio
  version: 202209.28.00 #202208.04.00
  x-summary: Schema dell'infortunio compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Bruno Marino
    email: b.marino@almawave.it
   # url:
  description:
    L'Infortunio sul lavoro viene definito quando l'evento scatenante è improvviso e violento e si riscontri il nesso di causalità con il lavoro svolto.
    L'assicurazione obbligatoria Inail copre ogni evento avvenuto per "causa violenta in occasione di lavoro" dal quale derivi la morte,
    l'inabilità permanente o l'inabilità assoluta temporanea per più di tre giorni.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    IdInfortunio:
      type: string
      description: Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        http://dati.inail.it/ontology/idInfortunio
      example: "111000000"
      maxLength: 50
      minLength: 1
    Infortunio:
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/Infortunio
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        id_infortunio: idInfortunio
        tipo_infortunio: tipoInfortunio
        data_riferimento_infortunio: dataRiferimentoInfortunio
        infortunio_accaduto_in_tipoLuogo:
          "@id": infortunioAccadutoInTipoLuogo
        infortunio_accaduto_a_infortunato:
          "@id": infortunioAccadutoAInfortunato
      additionalProperties: true
      description:
          Questo schema rappresenta un infortunio
          ed è associato ad  http://dati.inail.it/ontology/Infortunio
      required:
      - tipo_infortunio
      - data_riferimento_infortunio
      - id_infortunio
      properties:
        id_infortunio:
          $ref: "#/components/schemas/IdInfortunio"
        data_riferimento_infortunio:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        tipo_infortunio:
          maxLength: 255
          type: string
        infortunio_accaduto_in_tipoLuogo:
          type: object
          items:
            $ref: "#/components/schemas/TipoLuogoAccadimento"
        infortunio_accaduto_a_infortunato:
          type: object
          items:
            $ref: "#/components/schemas/Infortunato"
      example:
        id_infortunio: "111000000"
        data_riferimento_infortunio: "2022-08-25"
        tipo_infortunio: "In itinere con mezzo di trasporto"
        infortunio_accaduto_in_tipoLuogo:
          categoria_tipo_luogo: "cantiere di costruzione, cava, miniera a cielo aperto"
          descrizione_tipo_luogo: "all'esterno - campo sportivo, piscina, pista di sci"
        infortunio_accaduto_a_infortunato:
          codice_soggetto_evento_lesivo: 1234
          eta_all_accadimento: 23

    CodiceSoggettoEventoLesivo:
      type: integer
      format: int64
      description: Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        Associato a http://dati.inail.it/ontology/codiceSoggettoEventoLesivo.
      example: 1234

    Infortunato:
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/Infortunato
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        codice_soggetto_evento_lesivo: codiceSoggettoEventoLesivo
        eta_all_accadimento: etaAllAccadimento
      additionalProperties: true
      description:
          Questo schema rappresenta un infortunato.
      required:
      - eta_all_accadimento
      - codice_soggetto_evento_lesivo
      properties:
        codice_soggetto_evento_lesivo:
          $ref: "#/components/schemas/CodiceSoggettoEventoLesivo"
        eta_all_accadimento:
          format: double
          type: number
      example:
        codice_soggetto_evento_lesivo: 1234
        eta_all_accadimento: 23

    CategoriaTipoLuogo:
      type: string
      description: Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        http://dati.inail.it/ontology/categoriaTipoLuogo
      example: "INF01"
      maxLength: 100
      minLength: 1

    TipoLuogoAccadimento:
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/TipoLuogoAccadimento
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        categoria_tipo_luogo: categoriaTipoLuogo
        descrizione_tipo_luogo: descrizioneTipoLuogo
      additionalProperties: true
      description: Questo schema rappresenta un TipoLuogoAccadimento.
      required:
      - descrizione_tipo_luogo
      - categoria_tipo_luogo
      properties:
        categoria_tipo_luogo:
          $ref: "#/components/schemas/CategoriaTipoLuogo"
        descrizione_tipo_luogo:
          maxLength: 255
          type: string
      example:
        categoria_tipo_luogo: "cantiere di costruzione, cava, miniera a cielo aperto"
        descrizione_tipo_luogo: "all'esterno - campo sportivo, piscina, pista di sci"
