openapi: 3.0.3
info:
  title: Schema del Tipo Trattazione
  version: 202306.27.00
  x-summary: Schema del tipo di trattazione di un evento lesivo compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
   https://w3id.org/italia/work-accident/onto/adm_serv/TipoTrattazioneINAIL
paths: {}
servers: []
tags: []
components:
  schemas:
    IdTipoTrattazione:
      type: string
      description:
          https://w3id.org/italia/work-accident/onto/adm_serv/codiceTipoTrattazione.
      example: 'AC'
      maxLength: 20
    TipoTrattazione:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/adm_serv/TipoTrattazioneINAIL
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/adm_serv/"
        codice_tipo_trattazione: codiceTipoTrattazione
        indicatore_tipo_trattazione: indicatoreTipoTrattazione
        descrizione_tipo_trattazione: descrizioneTipoTrattazione
      additionalProperties: true
      description:
          https://w3id.org/italia/work-accident/onto/adm_serv/TipoTrattazioneINAIL.
      required:
      - codice_tipo_trattazione
      - indicatore_tipo_trattazione
      - descrizione_tipo_trattazione
      properties:
        codice_tipo_trattazione:
           $ref: "#/components/schemas/IdTipoTrattazione"
        indicatore_tipo_trattazione:
          type: string
          maxLength: 50
        descrizione_tipo_trattazione:
          type: string
          maxLength: 255
      example:
        codice_tipo_trattazione: 'AC'
        indicatore_tipo_trattazione: 'E'
        descrizione_tipo_trattazione: 'Assegno continuativo mensile'