#
# Define running hooks.
#
- id: ttlfmt
  name: ttlfmt
  entry: ttlfmt
  files: >-
    ^assets/.*\.ttl
  types:
  - file
  language: python
  additional_dependencies:
  - rdflib
  - ttlser
  - ttlser[ttlfmt]
