openapi: 3.0.3
info:
  title: Schema della malattia professionale
  version: 202209.28.00
  x-summary: Schema della malattia professionale compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Bruno Marino
    email: b.marino@almawave.it
   # url:
  description: |-
    La malattia professionale è una patologia la cui causa agisce lentamente e progressivamente sull'organismo (causa diluita e non causa violenta e concentrata nel tempo).
    La stessa causa deve essere diretta ed efficiente, cioè in grado di produrre l'infermità in modo esclusivo o prevalente:
    il Testo Unico, infatti, parla di malattie contratte nell'esercizio e a causa delle lavorazioni rischiose.
    È ammesso, tuttavia, il concorso di cause extraprofessionali, purché queste non interrompano il nesso causale in quanto capaci di produrre da sole l'infermità.
    Per le malattie professionali, quindi, non basta l'occasione di lavoro come per gli infortuni, cioè un rapporto anche mediato o indiretto con il rischio lavorativo,
    ma deve esistere un rapporto causale, o concausale, diretto tra il rischio professionale e la malattia.
    Il rischio può essere provocato dalla lavorazione che l'assicurato svolge, oppure dall'''ambiente in cui la lavorazione stessa si svolge (cosiddetto "rischio ambientale").

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    IdMalattiaProfessionale:
      type: string
      description: Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        http://dati.inail.it/ontology/idMalattiaProfessionale
      example: "111000000"
      maxLength: 50
      minLength: 1
    MalattiaProfessionale:
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/MalattiaProfessionale
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        id_malattia: idMalattiaProfessionale
        esito_riconoscimento: esitoRiconoscimentoMalattiaProfessionale
        data_riferimento_malattia: dataRiferimentoMalattiaProfessionale
        importo_indennizzo: importoMalattiaProfessionale
        codice_settore_malattia: codiceSettoreCorrelatoMalattiaProfessionale
        codice_subsettore_malattia: codiceSubsettoreCorrelatoMalattiaProfessionale
        definizione_malattia: definizioneAmministrativaMalattiaProfessionale
        grado_inabilita_assunto:
          "@id": malattiaProfessionaleHaGradoDiInabilitaAssunto
        grado_inabilita_attuale:
          "@id": malattiaProfessionaleHaGradoDiInabilitaAttuale
        malattia_accaduta_a_tecnopatico:
          "@id": malattiaProfessionaleRelativaATecnopatico
      additionalProperties: true
      description:
          Questo schema rappresenta una malattia professionale
          ed è associato ad  http://dati.inail.it/ontology/MalattiaProfessionale
      required:
      - id_malattia
      - esito_riconoscimento
      - data_riferimento_malattia
      - importo_indennizzo
      - codice_settore_malattia
      - codice_subsettore_malattia
      - definizione_malattia
      properties:
        id_malattia:
          $ref: "#/components/schemas/IdMalattiaProfessionale"
        esito_riconoscimento:
          maxLength: 50
          type: string
        data_riferimento_malattia:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        importo_indennizzo:
          type: number
          format: double
        codice_settore_malattia:
          type: integer
          format: int32
        codice_subsettore_malattia:
          type: integer
          format: int32
        definizione_malattia:
          maxLength: 50
          type: string
        grado_inabilita_assunto:
          type: object
          items:
            $ref: "#/components/schemas/GradoDiInabilita"
        grado_inabilita_attuale:
          type: object
          items:
            $ref: "#/components/schemas/GradoDiInabilita"
        malattia_accaduta_a_tecnopatico:
          type: object
          items:
            $ref: "#/components/schemas/Tecnopatico"
      example:
        id_malattia: "111000000"
        esito_riconoscimento: "riconosciuta"
        data_riferimento_malattia: "2015-04-14"
        importo_indennizzo: 0.00
        codice_settore_malattia: 1
        codice_subsettore_malattia: 1
        definizione_malattia: "In istruttoria"
        grado_inabilita_assunto:
          descrizione_inabilita: "003"
          percentuale_inabilita: 3
        grado_inabilita_attuale:
          descrizione_inabilita: "003"
          percentuale_inabilita: 3
        malattia_accaduta_a_tecnopatico:
          codice_soggetto_evento_lesivo: 12345678
          eta_all_accadimento: 23

    GradoDiInabilita:
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/GradoDiInabilita
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        descrizione_inabilita: descrizioneGradoDiInabilita
        percentuale_inabilita: percentualeGradoDiInabilita
      additionalProperties: true
      description:
          Questo schema rappresenta il grado di inabilità relativo alla malattia professionale.
      required:
      - descrizione_inabilita
      - percentuale_inabilita
      properties:
        descrizione_inabilita:
          type: string
          maxLength: 10
        percentuale_inabilita:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
      example:
        descrizione_inabilita: "003"
        percentuale_inabilita: 3

    CodiceSoggettoEventoLesivo:
      type: integer
      format: int64
      description: Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        Associato a http://dati.inail.it/ontology/codiceSoggettoEventoLesivo.
      example: 12345678

    Tecnopatico:
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/Tecnopatico
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        codice_soggetto_evento_lesivo: codiceSoggettoEventoLesivo
        eta_all_accadimento: etaAllAccadimento
      additionalProperties: true
      description:
          Questo schema rappresenta un tecnopatico.
      required:
      - eta_all_accadimento
      - codice_soggetto_evento_lesivo
      properties:
        codice_soggetto_evento_lesivo:
          $ref: "#/components/schemas/CodiceSoggettoEventoLesivo"
        eta_all_accadimento:
          type: integer
          format: int32
      example:
        codice_soggetto_evento_lesivo: 12345678
        eta_all_accadimento: 23
