openapi: 3.0.3
info:
  title: Schema della pratica relativa alla richiesta del documento PD DA1
  version: 202308.31.00
  x-summary: Schema della pratica relativa alla richiesta del documento PD DA1 compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
   https://w3id.org/italia/work-accident/onto/proc6_pdda1/PraticaPDDA1
paths: {}
servers: []
tags: []
components:
  schemas:

    DocumentoPdda1:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/documento-pdda1/latest/documento-pdda1.oas3.yaml#/components/schemas/DocumentoPdda1"
    SedeInail:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/sede-inail/latest/sede-inail.oas3.yaml#/components/schemas/SedeInail"

    IdPratica:
      type: integer
      format: int64
      description:
        https://w3id.org/italia/work-accident/onto/proc6_pdda1/codicePraticaPDDA1
      example: 111000000

    PraticaPdda1:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/proc6_pdda1/PraticaPDDA1
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/proc6_pdda1/"
        codice_pratica_pdda1: codicePraticaPDDA1
        pratica_genera_documento_pdda1:
          "@id": praticaGeneraDocumentoPDDA1
        pratica_elaborata_da_sede:
          "@id": praticaElaborataDaSedeINAIL
      additionalProperties: true
      description:
         https://w3id.org/italia/work-accident/onto/proc6_pdda1/PraticaPDDA1
      required:
      - codice_pratica_pdda1
      properties:
        codice_pratica_pdda1:
          $ref: "#/components/schemas/IdPratica"
        pratica_genera_documento_pdda1:
          type: object
          items:
            $ref: "#/components/schemas/DocumentoPdda1"
        pratica_elaborata_da_sede:
          type: object
          items:
            $ref: "#/components/schemas/SedeInail"
      example:
        codice_pratica_pdda1: 111000000
        pratica_genera_documento_pdda1:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/documento-pdda1/latest/documento-pdda1.oas3.yaml#/components/schemas/DocumentoPdda1/example"
        pratica_elaborata_da_sede:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/sede-inail/latest/sede-inail.oas3.yaml#/components/schemas/SedeInail/example"

