openapi: 3.0.3
info:
  title: Schema della Trattazione
  version: 202306.27.00
  x-summary: Schema della trattazione di un evento lesivo compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
   https://w3id.org/italia/work-accident/onto/adm_serv/TrattazioneINAIL
paths: {}
servers: []
tags: []
components:
  schemas:
    EsitoDefinizione:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/esito-definizione/latest/esito-definizione.oas3.yaml#/components/schemas/EsitoDefinizione"
    MalattiaProfessionale:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/malattia-professionale/latest/malattia-professionale.oas3.yaml#/components/schemas/MalattiaProfessionale"
    Infortunio:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/infortunio/latest/infortunio.oas3.yaml#/components/schemas/Infortunio"
    TipoIndennizzo:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tipo-indennizzo/latest/tipo-indennizzo.oas3.yaml#/components/schemas/TipoIndennizzo"
    TipoTrattazione:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tipo-trattazione/latest/tipo-trattazione.oas3.yaml#/components/schemas/TipoTrattazione"

    IdTrattazione:
      type: integer
      format: int64
      description:
          https://w3id.org/italia/work-accident/onto/adm_serv/idTrattazione.
      example: 111000000

    Trattazione:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/adm_serv/TrattazioneINAIL
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/adm_serv/"
        id_trattazione: idTrattazione
        data_inizio_trattazione: dataInizioTrattazione
        data_fine_trattazione: dataFineTrattazione
        data_istruttoria_trattazione: dataUltimaDefinizioneDecisioneIstruttoriaTrattazione
        giorni_definizione_trattazione: numeroGiorniDefinizioneTrattazione
        qualifica_professionale: qualificaProfessionaleTrattazione
        tipo_istruttoria_sanitaria: tipoDecisioneIstruttoriaSanitariaTrattazione
        tipo_istruttoria_amministrativa: tipoDecisioneIstruttoriaAmministrativaTrattazione
        trattazione_esito:
          "@id": trattazioneHaEsitoDefinizione
        trattazione_decisione_istruttoria:
          "@id": trattazioneHaTipoDefinizioneDecisioneIstruttoria
        trattazione_tipo_indennizzo:
          "@id": trattazioneHaTipoIndennizzo
        trattazione_tipo_trattazione:
          "@id": haTipoTrattazione
        trattazione_relativa_a_mp:
          "@id": trattazioneRelativaAEvento
        trattazione_relativa_a_inf:
          "@id": trattazioneRelativaAEvento
      additionalProperties: true
      description:
          https://w3id.org/italia/work-accident/onto/adm_serv/TrattazioneINAIL.
      required:
      - id_trattazione
      - data_inizio_trattazione
      - data_fine_trattazione
      - data_istruttoria_trattazione
      - giorni_definizione_trattazione
      - qualifica_professionale
      - tipo_istruttoria_sanitaria
      - tipo_istruttoria_amministrativa
      properties:
        id_trattazione:
          $ref: "#/components/schemas/IdTrattazione"
        data_inizio_trattazione:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_fine_trattazione:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_istruttoria_trattazione:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        giorni_definizione_trattazione:
          type: integer
          format: int32
        qualifica_professionale:
          type: string
          maxLength: 50
        tipo_istruttoria_sanitaria:
          type: string
          maxLength: 50
        tipo_istruttoria_amministrativa:
          type: string
          maxLength: 50
        trattazione_esito:
          type: object
          items:
            $ref: "#/components/schemas/EsitoDefinizione"
        trattazione_decisione_istruttoria:
          type: object
          items:
            $ref: "#/components/schemas/TipoDefinizioneDecisioneIstruttoria"
        trattazione_tipo_indennizzo:
          type: object
          items:
            $ref: "#/components/schemas/TipoIndennizzo"
        trattazione_tipo_trattazione:
          type: object
          items:
            $ref: "#/components/schemas/TipoTrattazione"
        trattazione_relativa_a_mp:
          type: object
          items:
            $ref: "#/components/schemas/MalattiaProfessionale"
        trattazione_relativa_a_inf:
          type: object
          items:
            $ref: "#/components/schemas/Infortunio"
      example:
        id_trattazione: 111000000
        data_inizio_trattazione: '2016-05-15'
        data_fine_trattazione: '2016-06-20'
        data_istruttoria_trattazione: '2016-05-16'
        giorni_definizione_trattazione: 5
        qualifica_professionale: 'Non definito'
        tipo_istruttoria_sanitaria: 'Non definito'
        tipo_istruttoria_amministrativa: 'Non definito'
        trattazione_esito:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/esito-definizione/latest/esito-definizione.oas3.yaml#/components/schemas/EsitoDefinizione/example"
        trattazione_decisione_istruttoria:
          codice_decisione_istruttoria: 'AI'
          descrizione_decisione_istruttoria: 'Accolta INPS'
          esito_decisione_istruttoria: 'Negativo'
        trattazione_tipo_indennizzo:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tipo-indennizzo/latest/tipo-indennizzo.oas3.yaml#/components/schemas/TipoIndennizzo/example"
        trattazione_tipo_trattazione:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tipo-trattazione/latest/tipo-trattazione.oas3.yaml#/components/schemas/TipoTrattazione/example"
        trattazione_relativa_a_mp:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/malattia-professionale/latest/malattia-professionale.oas3.yaml#/components/schemas/MalattiaProfessionale/example"
        trattazione_relativa_a_inf:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/infortunio/latest/infortunio.oas3.yaml#/components/schemas/Infortunio/example"

    TipoDefinizioneDecisioneIstruttoria:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/adm_serv/TipoDefinizioneDecisioneIstruttoriaINAIL
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/adm_serv/"
        codice_decisione_istruttoria: codiceTipoDefinizioneDecisioneIstruttoria
        descrizione_decisione_istruttoria: descrizioneTipoDefinizioneDecisioneIstruttoria
        esito_decisione_istruttoria: esitoDecisioneIstruttoria
      additionalProperties: true
      description:
         https://w3id.org/italia/work-accident/onto/adm_serv/TipoDefinizioneDecisioneIstruttoriaINAIL.
      required:
      - codice_decisione_istruttoria
      - descrizione_decisione_istruttoria
      - esito_decisione_istruttoria
      properties:
        codice_decisione_istruttoria:
            type: string
            maxLength: 20
        descrizione_decisione_istruttoria:
          type: string
          maxLength: 50
        esito_decisione_istruttoria:
          type: string
          maxLength: 50
      example:
        codice_decisione_istruttoria: 'AI'
        descrizione_decisione_istruttoria: 'Accolta INPS'
        esito_decisione_istruttoria: 'Negativo'