openapi: 3.0.3
info:
  title: Schema del Tecnopatico
  version: 202301.10.00
  x-summary: Schema del tecnopatico compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Bruno Marino
    email: b.marino@almawave.it
   # url:
  description: |-
   Il tecnopatico è qualsiasi lavoratore affetto da malattia professionale.
   
    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    IdTecnopatico:
        type: integer
        format: int64
        description:
            Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
            Associato a https://w3id.org/italia/onto/WorkAccident/codiceSoggettoEventoLesivo.
        example: 12345678

    Tecnopatico:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/WorkAccident/Tecnopatico
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/WorkAccident/"
        id_tecnopatico: codiceSoggettoEventoLesivo
        eta_all_accadimento_tecnopatico: etaAllAccadimento
      additionalProperties: true
      description:
          Questo schema rappresenta un tecnopatico ed è associato ad https://w3id.org/italia/onto/WorkAccident/Tecnopatico.
      required:
      - id_tecnopatico
      - eta_all_accadimento_tecnopatico
      properties:
        id_tecnopatico:
          $ref: "#/components/schemas/IdTecnopatico"
        eta_all_accadimento_tecnopatico:
          type: integer
          format: int32
      example:
        id_tecnopatico: 12345678
        eta_all_accadimento_tecnopatico: 23