openapi: 3.0.3
info:
  title: Schema della richiesta relativa al documento PD DA1
  version: 202308.31.00
  x-summary: Schema della richiesta relativa al documento PD DA1 compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
   Modulo di richiesta per il PD DA1 che il datore di lavoro, il lavoratore autonomo o un incaricato per conto del datore effettua. Il PD DA1 può essere altresì richiesto dalla persona, titolare di una rendita INAIL derivante da infortunio sul lavoro o malattia professionale, che intenda trasferirsi all’estero anche se non più in attività lavorativa.
   La richiesta è effettuata accedendo al sito istituzionale, previa abilitazione, oppure inviando il modulo compilato, tramite PEC, alla Sede INAIL competente per territorio. La metadatazione semantica degli schemi si basa sul documento [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html) che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:

    PraticaPdda1:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/pratica-pdda1/latest/pratica-pdda1.oas3.yaml#/components/schemas/PraticaPdda1"
    SedeInail:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/sede-inail/latest/sede-inail.oas3.yaml#/components/schemas/SedeInail"

    IdRichiesta:
      type: integer
      format: int64
      description:
        Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        Associato a https://w3id.org/italia/work-accident/onto/proc6_pdda1/codiceRichiestaPDDA1
      example: 111000000

    RichiestaPdda1:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/proc6_pdda1/RichiestaDocumentoPDDA1
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/proc6_pdda1/"
        codice_richiesta_pdda1: codiceRichiestaPDDA1
        data_richiesta_pdda1: dataRichiestaPDDA1
        data_inizio_permanenza_estero: dataInizioPermanenzaEstero
        data_fine_permanenza_estero: dataFinePermanenzaEstero
        richiesta_inviata_sede_inail:
          "@id": richiestaInviataASedeINAIL
        richiesta_ha_pratica:
          "@id": richiestaHaPraticaPDDA1
      additionalProperties: true
      description:
         Questo schema rappresenta la richiesta del documento PD DA1 ed è associato ad https://w3id.org/italia/work-accident/onto/proc6_pdda1/RichiestaDocumentoPDDA1.
      required:
      - codice_richiesta_pdda1
      - data_richiesta_pdda1
      - data_inizio_permanenza_estero
      - data_fine_permanenza_estero
      properties:
        codice_richiesta_pdda1:
          $ref: "#/components/schemas/IdRichiesta"
        data_richiesta_pdda1:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_inizio_permanenza_estero:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_fine_permanenza_estero:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        richiesta_inviata_sede_inail:
          type: object
          items:
            $ref: "#/components/schemas/SedeInail"
        richiesta_ha_pratica:
          type: object
          items:
            $ref: "#/components/schemas/PraticaPdda1"
      example:
        codice_richiesta_pdda1: 111000000
        data_richiesta_pdda1: '2022-08-05'
        data_inizio_permanenza_estero: '2022-08-30'
        data_fine_permanenza_estero: '2022-09-30'
        richiesta_inviata_sede_inail:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/sede-inail/latest/sede-inail.oas3.yaml#/components/schemas/SedeInail/example"
        richiesta_ha_pratica:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/pratica-pdda1/latest/pratica-pdda1.oas3.yaml#/components/schemas/PraticaPdda1/example"

