openapi: 3.0.3
info:
  title: Schema dell'Indennizzo
  version: 202306.27.00
  x-summary: Schema dell'indennizzo compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
   https://w3id.org/italia/work-accident/onto/adm_serv/IndennizzoINAIL
paths: {}
servers: []
tags: []
components:
  schemas:

    IdIndennizzo:
      type: integer
      format: int64
      description:
          https://w3id.org/italia/work-accident/onto/adm_serv/idPrestazioneEconomica
      example: 001234567

    Indennizzo:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/adm_serv/IndennizzoINAIL
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/adm_serv/"
        id_indennizzo: idPrestazioneEconomica
        codice_indennizzo: codiceIndennizzo
        causale_pagamento: causalePagamentoIndennizzo
        tipo_riapertura: tipoRiaperturaIndennizzo
        data_proposta_pagamento: dataPropostaPagamentoIndennizzo
        data_inizio_trattazione: dataInizioTrattazioneIndennizzo
        data_liquidazione_indennizzo: dataLiquidazioneIndennizzo
        indennizzo_giornaliero_ha_inabilita:
          "@id": indennizzoGiornalieroHaInabilita
      additionalProperties: true
      description:
           https://w3id.org/italia/work-accident/onto/adm_serv/IndennizzoINAIL
      required:
        - id_indennizzo
        - codice_indennizzo
        - causale_pagamento
        - tipo_riapertura
        - data_proposta_pagamento
        - data_inizio_trattazione
        - data_liquidazione_indennizzo
      properties:
        id_indennizzo:
          $ref: "#/components/schemas/IdIndennizzo"
        codice_indennizzo:
          type: string
          maxLength: 10
        causale_pagamento:
          type: string
          maxLength: 255
        tipo_riapertura:
          type: string
          maxLength: 255
        data_proposta_pagamento:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_inizio_trattazione:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_liquidazione_indennizzo:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      example:
        id_indennizzo: 001234567
        codice_indennizzo: "TE"
        causale_pagamento: "Causale pagamento indennizzo"
        tipo_riapertura: "Citazione"
        data_proposta_pagamento: "2020-11-12"
        data_inizio_trattazione: "2020-09-01"
        data_liquidazione_indennizzo: "2020-11-12"