openapi: 3.0.3
info:
  title: Schema dell'Inabilità Temporanea
  version: 202211.10.00
  x-summary: Schema dell'inabilità temporanea compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Bruno Marino
    email: b.marino@almawave.it
   # url:
  description: |-
   L'inabilità temporanea è l'incapacità di svolgere per un periodo di tempo limitato la propria attività lavorativa. Può essere causata da un infortunio sul lavoro o, in qualche caso, da una malattia professionale.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    MalattiaProfessionale:
      $ref: "https://github.com/InailUfficio5/inail-ndc/tree/main/assets/schemas/malattia-professionale/malattia-professionale.oas3.yaml#/components/schemas/MalattiaProfessionale"
    Infortunio:
      $ref: "https://github.com/InailUfficio5/inail-ndc/tree/main/assets/schemas/infortunio/infortunio.oas3.yaml#/components/schemas/Infortunio"
    TipoTrattazione:
      $ref: "https://github.com/InailUfficio5/inail-ndc/tree/main/assets/schemas/tipo-trattazione/tipo-trattazione.oas3.yaml#/components/schemas/TipoTrattazione"
    Infortunato:
      $ref: "https://github.com/InailUfficio5/inail-ndc/tree/main/assets/schemas/infortunato/infortunato.oas3.yaml#/components/schemas/Infortunato"
    Tecnopatico:
      $ref: "https://github.com/InailUfficio5/inail-ndc/tree/main/assets/schemas/tecnopatico/tecnopatico.oas3.yaml#/components/schemas/Tecnopatico"
    IdInabilitaTemporanea:
      type: string
      description:
          Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
          Associato a https://w3id.org/italia/onto/WorkAccident/idInabilitaTemporanea.
      example: '111000000'
      maxLength: 50
      minLength: 1
    InabilitaTemporanea:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/WorkAccident/InabilitaTemporanea
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/WorkAccident/"
        id_inabilita: idInabilitaTemporanea
        data_inizio_inabilita: dataInizioInabilitaTemporanea
        data_apertura_inabilita: dataAperturaInabilitaTemporanea
        giorni_inabilita: numeroGiorniInabilitaTemporanea
        data_definizione_inabilita: dataDefinizioneInabilitaTemporanea
        data_fine_inabilita: dataFineInabilitaTemporanea
        inabilita_riferita_a_infortunato:
          "@id": inabilitaRiferitaASoggetto
        inabilita_riferita_a_tecnopatico:
          "@id": inabilitaRiferitaASoggetto
        inabilita_trattazione:
          "@id": inabilitaRelativaATipoTrattazione
        inabilita_causata_da_mp:
          "@id": inabilitaCausataDaEvento
        inabilita_causata_da_inf:
          "@id": inabilitaCausataDaEvento
      additionalProperties: true
      description:
         Questo schema rappresenta l'inabilità temporanea ed è associato a https://w3id.org/italia/onto/WorkAccident/InabilitaTemporanea.
      required:
      - id_inabilita
      - data_inizio_inabilita
      - data_apertura_inabilita
      - giorni_inabilita
      - data_definizione_inabilita
      - data_fine_inabilita
      properties:
        id_inabilita:
          $ref: "#/components/schemas/IdInabilitaTemporanea"
        data_inizio_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_apertura_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        giorni_inabilita:
          type: integer
          format: int32
        data_definizione_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_fine_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        inabilita_riferita_a_infortunato:
          type: object
          items:
            $ref: "#/components/schemas/Infortunato"
        inabilita_riferita_a_tecnopatico:
          type: object
          items:
            $ref: "#/components/schemas/Tecnopatico"
        inabilita_trattazione:
          type: object
          items:
            $ref: "#/components/schemas/TipoTrattazione"
        inabilita_causata_da_mp:
          type: object
          items:
            $ref: "#/components/schemas/MalattiaProfessionale"
        inabilita_causata_da_inf:
          type: object
          items:
            $ref: "#/components/schemas/Infortunio"
      example:
        id_inabilita: '111000000'
        data_inizio_inabilita: '2015-04-14'
        data_apertura_inabilita: '2015-04-18'
        giorni_inabilita: 4
        data_definizione_inabilita: '2015-04-14'
        data_fine_inabilita: '2015-04-22'
        inabilita_soggetto:
        inabilita_riferita_a_infortunato:
          - $ref: "#/components/schemas/Infortunato/example"
        inabilita_riferita_a_tecnopatico:
          - $ref: "#/components/schemas/Tecnopatico/example"
        inabilita_trattazione:
          - $ref: "#/components/schemas/TipoTrattazione/example"
        inabilita_causata_da_mp:
          - $ref: "#/components/schemas/MalattiaProfessionale/example"
        inabilita_causata_da_inf:
          - $ref: "#/components/schemas/Infortunio/example"

