openapi: 3.0.3
info:
  title: Schema dell'inabilità temporanea
  version: 202210.04.00
  x-summary: Schema dell'inabilità temporanea compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Bruno Marino
    email: b.marino@almawave.it
   # url:
  description: |-
    L'inabilità temporanea  può essere causata da un infortunio o da una malattia ed è l'incapacità a svolgere per un periodo di tempo limitato la propria attività lavorativa.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    IdInabilitaTemporanea:
      type: string
      description: Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        http://dati.inail.it/ontology/idInabilitaTemporanea
      example: "111000000"
      maxLength: 50
      minLength: 1
    InabilitaTemporanea:
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/InabilitaTemporanea
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        id_inabilita: idInabilitaTemporanea
        data_inizio_inabilita: dataInizioInabilitaTemporanea
        data_apertura_inabilita: dataAperturaInabilitaTemporanea
        giorni_inabilita: numeroGiorniInabilitaTemporanea
        data_definizione_inabilita: dataDefinizioneInabilitaTemporanea
        data_fine_inabilita: dataFineInabilitaTemporanea
        inabilita_soggetto:
          "@id": inabilitaRiferitaASoggetto
        inabilita_da_evento:
          "@id": inabilitaCausataDaEvento
        inabilita_trattazione:
          "@id": inabilitaRelativaATipoTrattazione
      additionalProperties: true
      description:
          Questo schema rappresenta un'inabilità temporanea
          ed è associato ad  http://dati.inail.it/ontology/InabilitaTemporanea
      required:
      - id_inabilita
      - data_inizio_inabilita
      - data_apertura_inabilita
      - giorni_inabilita
      - data_definizione_inabilita
      - data_fine_inabilita
      properties:
        id_inabilita:
          $ref: "#/components/schemas/IdInabilitaTemporanea"
        data_inizio_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_apertura_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        giorni_inabilita:
          type: integer
          format: int32
        data_definizione_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_fine_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        inabilita_soggetto:
          type: object
          items:
            $ref: "#/components/schemas/SoggettoEventoLesivo"
        inabilita_da_evento:
          type: object
          items:
            $ref: "#/components/schemas/EventoLesivo"
        inabilita_trattazione:
          type: object
          items:
            $ref: "#/components/schemas/TipoTrattazione"
      example:
        id_inabilita: "111000000"
        data_inizio_inabilita: "2015-04-14"
        data_apertura_inabilita: "2015-04-18"
        giorni_inabilita: 4
        data_definizione_inabilita: "2015-04-14"
        data_fine_inabilita: "2015-04-22"
        inabilita_soggetto:
          codice_soggetto_evento_lesivo: 1234
          eta_all_accadimento: 23
        inabilita_da_evento:
          descrizione_inabilita: "00012345"
          percentuale_inabilita: 3
        inabilita_trattazione:
          codice_soggetto_evento_lesivo: 1234
          eta_all_accadimento: 23

    CodiceSoggettoEventoLesivo:
      type: string
      maxLength: 50
      description: Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        Associato a http://dati.inail.it/ontology/codiceSoggettoEventoLesivo.
      example: "00012345"

    SoggettoEventoLesivo: #link con altri schema
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/SoggettoEventoLesivo
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        codice_soggetto_evento_lesivo: codiceSoggettoEventoLesivo
        eta_all_accadimento: etaAllAccadimento
      additionalProperties: true
      description:
          Questo schema rappresenta un soggetto evento lesivo.
      required:
      - eta_all_accadimento
      - codice_soggetto_evento_lesivo
      properties:
        codice_soggetto_evento_lesivo:
          $ref: "#/components/schemas/CodiceSoggettoEventoLesivo"
        eta_all_accadimento:
          type: integer
          format: int32
      example:
        codice_soggetto_evento_lesivo: "1234"
        eta_all_accadimento: 23

    CodiceCaso:
          type: string
          maxLength: 50
          description: Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
            Associato a http://dati.inail.it/ontology/codiceCaso.
          example: "00012345"

    EventoLesivo:     # link con altri schema
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/EventoLesivo
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        codice_caso: codiceCaso
        additionalProperties: true
        description:
            Questo schema rappresenta un evento lesivo.
      required:
      - codice_caso
      properties:
        codice_caso:
          $ref: "#/components/schemas/CodiceCaso"
      example:
        codice_caso: "00012345"

    TipoTrattazione:
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/TipoTrattazione
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        codice_tipo_trattazione: codiceTipoTrattazione
        indicatore_tipo_trattazione: indicatoreTipoTrattazione
        descrizione_tipo_trattazione: descrizioneTipoTrattazione
      additionalProperties: true
      description:
          Questo schema rappresenta il tipo di trattazione relativo all'inabilità temporanea.
      required:
      - codice_tipo_trattazione
      - indicatore_tipo_trattazione
      - descrizione_tipo_trattazione
      properties:
        codice_tipo_trattazione:
          type: string
          maxLength: 20
        indicatore_tipo_trattazione:
          type: string
          maxLength: 50
        descrizione_tipo_trattazione:
          type: string
          maxLength: 255
      example:
        codice_tipo_trattazione: "00012345"
        indicatore_tipo_trattazione: ""
        descrizione_tipo_trattazione: ""
