openapi: 3.0.3
info:
  title: Schema della Prestazione Economica
  version: 202306.27.00
  x-summary: Schema della prestazione economica compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
   https://w3id.org/italia/work-accident/onto/adm_serv/PrestazioneEconomicaINAIL
paths: {}
servers: []
tags: []
components:
  schemas:
    MalattiaProfessionale:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/malattia-professionale/latest/malattia-professionale.oas3.yaml#/components/schemas/MalattiaProfessionale"
    Infortunio:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/infortunio/latest/infortunio.oas3.yaml#/components/schemas/Infortunio"

    IdPrestazioneEconomica:
      type: integer
      format: int64
      description:
          https://w3id.org/italia/work-accident/onto/adm_serv/idPrestazioneEconomica.
      example: 001234567

    PrestazioneEconomica:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/adm_serv/PrestazioneEconomicaINAIL
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/adm_serv/"
        id_prestazione: idPrestazioneEconomica
        importo_prestazione: importoPrestazione
        prestazione_relativa_a_mp:
          "@id": prestazioneRelativaAEvento
        prestazione_relativa_a_inf:
          "@id": prestazioneRelativaAEvento
      additionalProperties: true
      description:
           https://w3id.org/italia/work-accident/onto/adm_serv/PrestazioneEconomicaINAIL.
      required:
      - id_prestazione
      - importo_prestazione
      properties:
        id_prestazione:
          $ref: "#/components/schemas/IdPrestazioneEconomica"
        importo_prestazione:
          type: number
          format: double
        prestazione_relativa_a_mp:
          type: object
          items:
            $ref: "#/components/schemas/MalattiaProfessionale"
        prestazione_relativa_a_inf:
          type: object
          items:
            $ref: "#/components/schemas/Infortunio"
      example:
        id_prestazione: 001234567
        importo_prestazione: 377.01
        prestazione_relativa_a_mp:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/malattia-professionale/latest/malattia-professionale.oas3.yaml#/components/schemas/MalattiaProfessionale/example"
        prestazione_relativa_a_inf:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/infortunio/latest/infortunio.oas3.yaml#/components/schemas/Infortunio/example"