openapi: 3.0.3
info:
  title: Schema dell'Indennizzo
  version: 202211.10.00
  x-summary: Schema dell'indennizzo corrisposto dall'INAIL alla persona.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Bruno Marino
    email: b.marino@almawave.it
   # url:
  description: |-
   L'indennizzo è una prestazione economica che l'Inail corrisponde ad infortunati e tecnopatici nell'ambito del sistema assicurativo.
   Le tipologie principali di indennizzo sono l'indennità per inabilità temporanea assoluta al lavoro, l'indennizzo in capitale una tantum per menomazioni permanenti di grado compreso tra 6 e il 15%,
   la rendita diretta per menomazioni permanenti di grado compreso tra 16 e il 100%, la rendita a superstiti nel caso di morte riconducibile ad infortunio sul lavoro o malattia professionale.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    InabilitaTemporanea:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/tree/main/assets/schemas/inabilita-temporanea/inabilita-temporanea.oas3.yaml#/components/schemas/InabilitaTemporanea"
    IdIndennizzo:
      type: string
      description:
          Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
          Associato a https://w3id.org/italia/onto/WorkAccident/idPrestazioneEconomica.
      example: '001234567'
      maxLength: 50
      minLength: 1
    Indennizzo:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/WorkAccident/Indennizzo
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/WorkAccident/"
        id_indennizzo: idPrestazioneEconomica
        codice_indennizzo: codiceIndennizzo
        causale_pagamento: causalePagamentoIndennizzo
        tipo_riapertura: tipoRiaperturaIndennizzo
        data_proposta_pagamento: dataPropostaPagamentoIndennizzo
        data_inizio_trattazione: dataInizioTrattazioneIndennizzo
        data_liquidazione_indennizzo: dataLiquidazioneIndennizzo
        giorni_inabilita_temporanea: numeroGiorniInabilitaTemporaneaIndennizzoGiornaliero
        indennizzo_giornaliero_ha_inabilita:
          "@id": indennizzoGiornalieroHaInabilita
      additionalProperties: true
      description:
           Questo schema rappresenta l'indennizzo ed è associato a https://w3id.org/italia/onto/WorkAccident/Indennizzo.
      required:
        - id_indennizzo
        - codice_indennizzo
        - causale_pagamento
        - tipo_riapertura
        - data_proposta_pagamento
        - data_inizio_trattazione
        - data_liquidazione_indennizzo
      properties:
        id_indennizzo:
          $ref: "#/components/schemas/IdIndennizzo"
        codice_indennizzo:
          type: string
          maxLength: 10
        causale_pagamento:
          type: string
          maxLength: 255
        tipo_riapertura:
          type: string
          maxLength: 255
        data_proposta_pagamento:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_inizio_trattazione:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_liquidazione_indennizzo:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        giorni_inabilita_temporanea:
          type: integer
          format: int64
        indennizzo_giornaliero_ha_inabilita:
          type: object
          items:
            $ref: "#/components/schemas/InabilitaTemporanea"
      example:
        id_indennizzo: '001234567'
        codice_indennizzo: "TE"
        causale_pagamento: "Causale pagamento indennizzo"
        tipo_riapertura: "Citazione"
        data_proposta_pagamento: "2020-11-12"
        data_inizio_trattazione: "2020-09-01"
        data_liquidazione_indennizzo: "2020-11-12"
        giorni_inabilita_temporanea: 10
        indennizzo_giornaliero_ha_inabilita:
          - $ref: "#/components/schemas/InabilitaTemporanea/example"
