openapi: 3.0.3
info:
  title: Schema dell'indennizzo
  version: 202209.29.00
  x-summary: Schema dell'indennizzo corrisposto dall'INAIL alla persona.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Bruno Marino
    email: b.marino@almawave.it
   # url:
  description: |-
    L'indennizzo è la prestazione economica che l'Inail corrisponde ad infortunati o tecnopatici; sono 4 le modalità principali con cui viene erogata la prestazione: in temporanea, in capitale, in rendita diretta e in rendita a superstiti.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    IdPrestazioneEconomica:
      type: string
      description: Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        http://dati.inail.it/ontology/idPrestazioneEconomica
      example: "s_cod_caso: 111000000"
      maxLength: 50
      minLength: 1
    Indennizzo:
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/Indennizzo
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        id_indennizzo: idPrestazioneEconomica
        codice_indennizzo: codiceIndennizzo
        causale_pagamento: causalePagamentoIndennizzo
        tipo_riapertura: tipoRiaperturaIndennizzo
        data_proposta_pagamento: dataPropostaPagamentoIndennizzo
        data_inizio_trattazione: dataInizioTrattazioneIndennizzo
        data_liquidazione_indennizzo: dataLiquidazioneIndennizzo
        giorni_inabilita_temporanea: numeroGiorniInabilitaTemporaneaIndennizzoGiornaliero
      additionalProperties: true
      description:
          Questo schema rappresenta un Indennizzo
          ed è associato ad  http://dati.inail.it/ontology/Indennizzo
      required:
        - id_indennizzo
        - codice_indennizzo
        - causale_pagamento
        - tipo_riapertura
        - data_proposta_pagamento
        - data_inizio_trattazione
        - data_liquidazione_indennizzo
      properties:
        id_indennizzo:
          $ref: "#/components/schemas/IdPrestazioneEconomica"
        codice_indennizzo:
          type: string
          maxLength: 10
        causale_pagamento:
          type: string
          maxLength: 255
        tipo_riapertura:
          type: string
          maxLength: 255
        data_proposta_pagamento:
          type: string
          format: date
        data_inizio_trattazione:
          type: string
          format: date
        data_liquidazione_indennizzo:
          type: string
          format: date
        giorni_inabilita_temporanea:
          type: integer
          format: int64
      example:
        id_indennizzo: "id: 12345"
        codice_indennizzo: "TE"
        causale_pagamento: "Causale pagamento indennizzo"
        tipo_riapertura: "tipo riapertura"
        data_proposta_pagamento: "2020-11-12"
        data_inizio_trattazione: "2020-09-01"
        data_liquidazione_indennizzo: "2020-11-12"
        giorni_inabilita_temporanea: 10
