openapi: 3.0.3
info:
  title: Schema dell'Esito Definizione
  version: 202306.27.00
  x-summary: Schema dell'esito di definizione di un evento lesivo compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
   https://w3id.org/italia/work-accident/onto/adm_serv/EsitoDefinizioneINAIL
paths: {}
servers: []
tags: []
components:
  schemas:

    IdEsitoDefinizione:
      type: string
      maxLength: 20
      description: https://w3id.org/italia/work-accident/onto/adm_serv/codiceEsitoDefinizione.
      example: 'CO'

    EsitoDefinizione:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/adm_serv/EsitoDefinizioneINAIL
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/adm_serv/"
        codice_esito_definizione: codiceEsitoDefinizione
        descrizione_esito_definizione: descrizioneEsitoDefinizione
        codice_classificazione_esito_definizione: codiceClassificazioneEsitoDefinizione
        descrizione_classificazione_esito_definizione: descrizioneClassificazioneEsitoDefinizione
      additionalProperties: true
      description:
          https://w3id.org/italia/work-accident/onto/adm_serv/EsitoDefinizioneINAIL.
      required:
      - codice_esito_definizione
      - descrizione_esito_definizione
      - codice_classificazione_esito_definizione
      - descrizione_classificazione_esito_definizione
      properties:
        codice_esito_definizione:
          $ref: "#/components/schemas/IdEsitoDefinizione"
        descrizione_esito_definizione:
          type: string
          maxLength: 255
        codice_classificazione_esito_definizione:
          type: string
          maxLength: 20
        descrizione_classificazione_esito_definizione:
          type: string
          maxLength: 255
      example:
        codice_esito_definizione: 'CO'
        descrizione_esito_definizione: 'Comunicazione istruttoria'
        codice_classificazione_esito_definizione: 'I'
        descrizione_classificazione_esito_definizione: 'Istruttoria'