openapi: 3.0.3
info:
  title: Schema del documento PD DA1
  version: 202308.31.00
  x-summary: Schema del documento PD DA1 compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
   Il PD DA1 è il Documento Portabile (PD) che dà diritto alla copertura sanitaria in caso di infortunio sul lavoro o di malattia professionale ed è destinato alla persona che si sposta, risiede o soggiorna in uno Stato membro dell'Unione Europea diverso da quello in cui è assicurata contro gli infortuni sul lavoro e le malattie professionali. La metadatazione semantica degli schemi si basa sul documento [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html) che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:

    IdDocumento:
      type: integer
      format: int64
      description:
        Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        Associato a https://w3id.org/italia/work-accident/onto/proc6_pdda1/numeroDocumento
      example: 111000000

    DocumentoPdda1:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/proc6_pdda1/DocumentoPDDA1
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/proc6_pdda1/"
        codice_documento_pdda1: numeroDocumentoPDDA1
        data_documento_pdda1: dataDocumentoPDDA1
        data_inizio_permanenza: dataInizioPermanenzaEstero
        data_fine_permanenza: dataFinePermanenzaEstero
        numero_giorni_pdda1: numeroGiorniPDDA1
      additionalProperties: true
      description:
         Questo schema rappresenta il documento PD DA1 ed è associato ad https://w3id.org/italia/work-accident/onto/proc6_pdda1/DocumentoPDDA1.
      required:
      - codice_documento_pdda1
      - data_documento_pdda1
      - data_inizio_permanenza
      - data_fine_permanenza
      - numero_giorni_pdda1
      properties:
        codice_documento_pdda1:
          $ref: "#/components/schemas/IdDocumento"
        data_documento_pdda1:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_inizio_permanenza:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_fine_permanenza:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        numero_giorni_pdda1:
          type: integer
          format: int32
      example:
        codice_documento_pdda1: 111000000
        data_documento_pdda1: '2022-08-25'
        data_inizio_permanenza: '2022-08-30'
        data_fine_permanenza: '2022-09-30'
        numero_giorni_pdda1: 32
