openapi: 3.0.3
info:
  title: Schema della Trattazione
  version: 202301.10.00
  x-summary: Schema della trattazione di un evento lesivo compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
   La trattazione identifica le diverse fasi della pratica di infortunio o di malattia professionale. Dagli esiti delle varie trattazioni si definisce il grado di invalidità, l'indennizzo e la prestazione che viene erogata agli aventi diritto.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    EsitoDefinizione:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/esito-definizione/esito-definizione.oas3.yaml#/components/schemas/EsitoDefinizione"
    MalattiaProfessionale:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/malattia-professionale/malattia-professionale.oas3.yaml#/components/schemas/MalattiaProfessionale"
    Infortunio:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/infortunio/infortunio.oas3.yaml#/components/schemas/Infortunio"
    TipoIndennizzo:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tipo-indennizzo/tipo-indennizzo.oas3.yaml#/components/schemas/TipoIndennizzo"
    TipoTrattazione:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tipo-trattazione/tipo-trattazione.oas3.yaml#/components/schemas/TipoTrattazione"

    IdTrattazione:
      type: string
      description:
          Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
          Associato a https://w3id.org/italia/onto/WorkAccident/idTrattazione.
      example: '111000000'
      maxLength: 50
      minLength: 1
    Trattazione:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/WorkAccident/Trattazione
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/WorkAccident/"
        id_trattazione: idTrattazione
        data_inizio_trattazione: dataInizioTrattazione
        data_fine_trattazione: dataFineTrattazione
        data_istruttoria_trattazione: dataUltimaDefinizioneDecisioneIstruttoriaTrattazione
        giorni_definizione_trattazione: numeroGiorniDefinizioneTrattazione
        qualifica_professionale: qualificaProfessionaleTrattazione
        tipo_istruttoria_sanitaria: tipoDecisioneIstruttoriaSanitariaTrattazione
        tipo_istruttoria_amministrativa: tipoDecisioneIstruttoriaAmministrativaTrattazione
        trattazione_esito:
          "@id": trattazioneHaEsitoDefinizione
        trattazione_decisione_istruttoria:
          "@id": trattazioneHaTipoDefinizioneDecisioneIstruttoria
        trattazione_tipo_indennizzo:
          "@id": trattazioneHaTipoIndennizzo
        trattazione_tipo_trattazione:
          "@id": haTipoTrattazione
        trattazione_relativa_a_mp:
          "@id": trattazioneRelativaAEvento
        trattazione_relativa_a_inf:
          "@id": trattazioneRelativaAEvento
      additionalProperties: true
      description:
          Questo schema rappresenta la trattazione di un evento lesivo
          ed è associato a https://w3id.org/italia/onto/WorkAccident/Trattazione.
      required:
      - id_trattazione
      - data_inizio_trattazione
      - data_fine_trattazione
      - data_istruttoria_trattazione
      - giorni_definizione_trattazione
      - qualifica_professionale
      - tipo_istruttoria_sanitaria
      - tipo_istruttoria_amministrativa
      properties:
        id_trattazione:
          $ref: "#/components/schemas/IdTrattazione"
        data_inizio_trattazione:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_fine_trattazione:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_istruttoria_trattazione:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        giorni_definizione_trattazione:
          type: integer
          format: int32
        qualifica_professionale:
          type: string
          maxLength: 50
        tipo_istruttoria_sanitaria:
          type: string
          maxLength: 50
        tipo_istruttoria_amministrativa:
          type: string
          maxLength: 50
        trattazione_esito:
          type: object
          items:
            $ref: "#/components/schemas/EsitoDefinizione"
        trattazione_decisione_istruttoria:
          type: object
          items:
            $ref: "#/components/schemas/TipoDefinizioneDecisioneIstruttoria"
        trattazione_tipo_indennizzo:
          type: object
          items:
            $ref: "#/components/schemas/TipoIndennizzo"
        trattazione_tipo_trattazione:
          type: object
          items:
            $ref: "#/components/schemas/TipoTrattazione"
        trattazione_relativa_a_mp:
          type: object
          items:
            $ref: "#/components/schemas/MalattiaProfessionale"
        trattazione_relativa_a_inf:
          type: object
          items:
            $ref: "#/components/schemas/Infortunio"
      example:
        id_trattazione: '111000000'
        data_inizio_trattazione: '2016-05-15'
        data_fine_trattazione: '2016-06-20'
        data_istruttoria_trattazione: '2016-05-16'
        giorni_definizione_trattazione: 5
        qualifica_professionale: 'Non definito'
        tipo_istruttoria_sanitaria: 'Non definito'
        tipo_istruttoria_amministrativa: 'Non definito'
        trattazione_esito:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/esito-definizione/esito-definizione.oas3.yaml#/components/schemas/EsitoDefinizione/example"
        trattazione_decisione_istruttoria:
          codice_decisione_istruttoria: 'AI'
          descrizione_decisione_istruttoria: 'Accolta INPS'
          esito_decisione_istruttoria: 'Negativo'
        trattazione_tipo_indennizzo:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tipo-indennizzo/tipo-indennizzo.oas3.yaml#/components/schemas/TipoIndennizzo/example"
        trattazione_tipo_trattazione:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tipo-trattazione/tipo-trattazione.oas3.yaml#/components/schemas/TipoTrattazione/example"
        trattazione_relativa_a_mp:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/malattia-professionale/malattia-professionale.oas3.yaml#/components/schemas/MalattiaProfessionale/example"
        trattazione_relativa_a_inf:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/infortunio/infortunio.oas3.yaml#/components/schemas/Infortunio/example"

    TipoDefinizioneDecisioneIstruttoria:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/WorkAccident/TipoDefinizioneDecisioneIstruttoria
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/WorkAccident/"
        codice_decisione_istruttoria: codiceTipoDefinizioneDecisioneIstruttoria
        descrizione_decisione_istruttoria: descrizioneTipoDefinizioneDecisioneIstruttoria
        esito_decisione_istruttoria: esitoDecisioneIstruttoria
      additionalProperties: true
      description:
         Questo schema rappresenta il tipo definizione decisione istruttoria relativo alla trattazione
          ed è associato a https://w3id.org/italia/onto/WorkAccident/TipoDefinizioneDecisioneIstruttoria.
      required:
      - codice_decisione_istruttoria
      - descrizione_decisione_istruttoria
      - esito_decisione_istruttoria
      properties:
        codice_decisione_istruttoria:
            type: string
            maxLength: 20
        descrizione_decisione_istruttoria:
          type: string
          maxLength: 50
        esito_decisione_istruttoria:
          type: string
          maxLength: 50
      example:
        codice_decisione_istruttoria: 'AI'
        descrizione_decisione_istruttoria: 'Accolta INPS'
        esito_decisione_istruttoria: 'Negativo'