openapi: 3.0.3
info:
  title: Schema dell'Inabilità Temporanea
  version: 202306.27.00
  x-summary: Schema dell'inabilità temporanea compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Anna Maria De Paoli
    email: a.depaoli@inail.it
   # url:
  description: |-
   https://w3id.org/italia/work-accident/onto/adm_serv/InabilitaTemporaneaINAIL
paths: {}
servers: []
tags: []
components:
  schemas:
    MalattiaProfessionale:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/malattia-professionale/latest/malattia-professionale.oas3.yaml#/components/schemas/MalattiaProfessionale"
    Infortunio:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/infortunio/latest/infortunio.oas3.yaml#/components/schemas/Infortunio"
    TipoTrattazione:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tipo-trattazione/latest/tipo-trattazione.oas3.yaml#/components/schemas/TipoTrattazione"
    Infortunato:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/infortunato/latest/infortunato.oas3.yaml#/components/schemas/Infortunato"
    Tecnopatico:
      $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tecnopatico/latest/tecnopatico.oas3.yaml#/components/schemas/Tecnopatico"

    IdInabilitaTemporanea:
      type: integer
      format: int64
      description:
          https://w3id.org/italia/work-accident/onto/adm_serv/idInabilitaTemporanea.
      example: 111000000

    InabilitaTemporanea:
      type: object
      x-jsonld-type: https://w3id.org/italia/work-accident/onto/adm_serv/InabilitaTemporaneaINAIL
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/work-accident/onto/adm_serv/"
        id_inabilita: idInabilitaTemporanea
        data_inizio_inabilita: dataInizioInabilitaTemporanea
        data_apertura_inabilita: dataAperturaInabilitaTemporanea
        giorni_inabilita: numeroGiorniInabilitaTemporanea
        data_definizione_inabilita: dataDefinizioneInabilitaTemporanea
        data_fine_inabilita: dataFineInabilitaTemporanea
        inabilita_riferita_a_infortunato:
          "@id": inabilitaRiferitaASoggetto
        inabilita_riferita_a_tecnopatico:
          "@id": inabilitaRiferitaASoggetto
        inabilita_trattazione:
          "@id": inabilitaRelativaATipoTrattazione
        inabilita_causata_da_mp:
          "@id": inabilitaCausataDaEvento
        inabilita_causata_da_inf:
          "@id": inabilitaCausataDaEvento
      additionalProperties: true
      description:
         https://w3id.org/italia/work-accident/onto/adm_serv/InabilitaTemporaneaINAIL.
      required:
      - id_inabilita
      - data_inizio_inabilita
      - data_apertura_inabilita
      - giorni_inabilita
      - data_definizione_inabilita
      - data_fine_inabilita
      properties:
        id_inabilita:
          $ref: "#/components/schemas/IdInabilitaTemporanea"
        data_inizio_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_apertura_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        giorni_inabilita:
          type: integer
          format: int32
        data_definizione_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_fine_inabilita:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        inabilita_riferita_a_infortunato:
          type: object
          items:
            $ref: "#/components/schemas/Infortunato"
        inabilita_riferita_a_tecnopatico:
          type: object
          items:
            $ref: "#/components/schemas/Tecnopatico"
        inabilita_trattazione:
          type: object
          items:
            $ref: "#/components/schemas/TipoTrattazione"
        inabilita_causata_da_mp:
          type: object
          items:
            $ref: "#/components/schemas/MalattiaProfessionale"
        inabilita_causata_da_inf:
          type: object
          items:
            $ref: "#/components/schemas/Infortunio"
      example:
        id_inabilita: 111000000
        data_inizio_inabilita: '2015-04-14'
        data_apertura_inabilita: '2015-04-18'
        giorni_inabilita: 4
        data_definizione_inabilita: '2015-04-14'
        data_fine_inabilita: '2015-04-22'
        inabilita_soggetto:
        inabilita_riferita_a_infortunato:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/infortunato/latest/infortunato.oas3.yaml#/components/schemas/Infortunato/example"
        inabilita_riferita_a_tecnopatico:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tecnopatico/latest/tecnopatico.oas3.yaml#/components/schemas/Tecnopatico/example"
        inabilita_trattazione:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/tipo-trattazione/latest/tipo-trattazione.oas3.yaml#/components/schemas/TipoTrattazione/example"
        inabilita_causata_da_mp:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/malattia-professionale/latest/malattia-professionale.oas3.yaml#/components/schemas/MalattiaProfessionale/example"
        inabilita_causata_da_inf:
          $ref: "https://raw.githubusercontent.com/InailUfficio5/inail-ndc/main/assets/schemas/infortunio/latest/infortunio.oas3.yaml#/components/schemas/Infortunio/example"
