openapi: 3.0.3
info:
  title: Schema della riapertura di una trattazione
  version: 202210.04.00
  x-summary: Schema della riapertura di una trattazione compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Bruno Marino
    email: b.marino@almawave.it
   # url:
  description: |-
    Una trattazione amministrativa giunge alla fine del suo iter burocratico ad una definizione e dall'esito della definizione scaturisce un provvedimento.
    La trattazione definita può essere sottoposta a riapertura e successiva ridefinizione.
    La riapertura viene effettuata sempre per volere del soggetto coinvolto nell'evento lesivo.
    Da una riapertura può scaturire un contenzioso, così come invece può essere risolta in ambito amministrativo.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    IdRiapertura:
      type: string
      description: Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        http://dati.inail.it/ontology/idRiapertura
      example: "111000000"
      maxLength: 50
      minLength: 1
    Riapertura:
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/Riapertura
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        id_riapertura: idRiapertura
        data_apertura_riapertura: dataAperturaRiapertura
        data_inizio_riapertura: dataInizioRiapertura
        data_inizio_trattazione_riapertura: dataInizioTrattazioneRiapertura
        data_fine_riapertura: dataFineRiapertura
        giorni_definizione_riapertura: numeroGiorniDefinizioneRiapertura
        motivazione_contenzioso: motivazioneContenziosoRiapertura
        tipo_riaperutra: tipoRiapertura
        tipo_conclusione_riapertura: tipoConclusioneRiapertura
        tipo_conclusione_precedente: tipoConclusionePrecedenteRiapertura
        riapertura_esito:
          "@id": riaperturaHaEsitoDefinizione
        riapertura_esito_trattazione:
          "@id": riaperturaHaEsitoDefinizioneTrattazione
        riapertura_tipo_trattazione:
          "@id": riaperturaRelativaATipoTrattazione
      additionalProperties: true
      description:
          Questo schema rappresenta la riapertura di una trattazione.
          ed è associato ad  http://dati.inail.it/ontology/Riapertura
      required:
      - id_riapertura
      - data_apertura_riapertura
      - data_inizio_riapertura
      - data_inizio_trattazione_riapertura
      - data_fine_riapertura
      - giorni_definizione_riapertura
      - motivazione_contenzioso
      - tipo_riaperutra
      - tipo_conclusione_riapertura
      - tipo_conclusione_precedente
      properties:
        id_riapertura:
          $ref: "#/components/schemas/IdRiapertura"
        data_apertura_riapertura:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_inizio_riapertura:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_inizio_trattazione_riapertura:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_fine_riapertura:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        giorni_definizione_riapertura:
          type: integer
          format: int32
        motivazione_contenzioso:
          type: string
          maxLength: 50
        tipo_riapertura:
          type: string
          maxLength: 50
        tipo_conclusione_riapertura:
          type: string
          maxLength: 50
        tipo_conclusione_precedente:
          type: string
          maxLength: 50
        riapertura_esito:
          type: object
          items:
            $ref: "#/components/schemas/EsitoDefinizione"
        riapertura_esito_trattazione:
          type: object
          items:
            $ref: "#/components/schemas/EsitoDefinizione"
        riapertura_tipo_trattazione:
          type: object
          items:
            $ref: "#/components/schemas/TipoTrattazione"
      example:
        id_riapertura: "111000000"
        data_apertura_riapertura: "1981-12-16"
        data_inizio_riapertura: "1997-11-06"
        data_inizio_trattazione_riapertura: "1981-12-16"
        data_fine_riapertura: "1998-11-05"
        giorni_definizione_riapertura: 512
        motivazione_contenzioso: "Percentuale di inabilità"
        tipo_riaperutra: "Citazione"
        tipo_conclusione_riapertura: "Non definito"
        tipo_conclusione_precedente: "Non definito"
        riapertura_esito:
          codice_esito_definizione: "CO"
          descrizione_esito_definizione: "Comunicazione istruttoria"
          codice_classificazione_esito_definizione: "I"
          descrizione_classificazione_esito_definizione: "Istruttoria"
        riapertura_esito_trattazione:
          codice_esito_definizione: "CO"
          descrizione_esito_definizione: "Comunicazione istruttoria"
          codice_classificazione_esito_definizione: "I"
          descrizione_classificazione_esito_definizione: "Istruttoria"
        riapertura_tipo_trattazione:
          codice_tipo_trattazione: "AC"
          indicatore_tipo_trattazione: "E"
          descrizione_tipo_trattazione: "Assegno continuativo mensile"

    EsitoDefinizione: #link con altri schema
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/EsitoDefinizione
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        codice_esito_definizione: codiceEsitoDefinizione
        descrizione_esito_definizione: descrizioneEsitoDefinizione
        codice_classificazione_esito_definizione: codiceClassificazioneEsitoDefinizione
        descrizione_classificazione_esito_definizione: descrizioneClassificazioneEsitoDefinizione
      additionalProperties: true
      description:
          Questo schema rappresenta l'esito definizione, ovvero la situazione amministrativa del caso.
      required:
      - codice_esito_definizione
      - descrizione_esito_definizione
      - codice_classificazione_esito_definizione
      - descrizione_classificazione_esito_definizione
      properties:
        codice_esito_definizione:
          type: string
          maxLength: 20
        descrizione_esito_definizione:
          type: string
          maxLength: 255
        codice_classificazione_esito_definizione:
          type: string
          maxLength: 20
        descrizione_classificazione_esito_definizione:
          type: string
          maxLength: 255
      example:
        codice_esito_definizione: "CO"
        descrizione_esito_definizione: "Comunicazione istruttoria"
        codice_classificazione_esito_definizione: "I"
        descrizione_classificazione_esito_definizione: "Istruttoria"

    TipoTrattazione: #link con altri schema
      type: object
      x-jsonld-type: http://dati.inail.it/ontology/TipoTrattazione
      x-jsonld-context:
        "@vocab": "http://dati.inail.it/ontology/"
        codice_tipo_trattazione: codiceTipoTrattazione
        indicatore_tipo_trattazione: indicatoreTipoTrattazione
        descrizione_tipo_trattazione: descrizioneTipoTrattazione
      additionalProperties: true
      description:
          Questo schema rappresenta il tipo di trattazione relativo all'inabilità temporanea.
      required:
      - codice_tipo_trattazione
      - indicatore_tipo_trattazione
      - descrizione_tipo_trattazione
      properties:
        codice_tipo_trattazione:
          type: string
          maxLength: 20
        indicatore_tipo_trattazione:
          type: string
          maxLength: 50
        descrizione_tipo_trattazione:
          type: string
          maxLength: 255
      example:
        codice_tipo_trattazione: "AC"
        indicatore_tipo_trattazione: "E"
        descrizione_tipo_trattazione: "Assegno continuativo mensile"
