openapi: 3.0.3
info:
  title: Schema dell'Infortunato
  version: 202301.10.00
  x-summary: Schema dell'infortunato compatibile con l'ontologia INAIL.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Bruno Marino
    email: b.marino@almawave.it
   # url:
  description: |-
   Per infortunato sul lavoro si intende ogni lavoratore con una lesione originata, in occasione di lavoro, da causa violenta che determini la morte della persona o che comprometta parzialmente o totalmente la capacità lavorativa.

    La metadatazione semantica degli schemi si basa sul documento
    [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
    che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    IdInfortunato:
        type: integer
        format: int64
        description:
            Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
            Associato a https://w3id.org/italia/onto/WorkAccident/codiceSoggettoEventoLesivo.
        example: 12345678

    Infortunato:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/WorkAccident/Infortunato
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/WorkAccident/"
        id_infortunato: codiceSoggettoEventoLesivo
        eta_all_accadimento_infortunato: etaAllAccadimento
      additionalProperties: true
      description:
          Questo schema rappresenta un infortunato ed è associato ad https://w3id.org/italia/onto/WorkAccident/Infortunato.
      required:
      - id_infortunato
      - eta_all_accadimento_infortunato
      properties:
        id_infortunato:
          $ref: "#/components/schemas/IdInfortunato"
        eta_all_accadimento_infortunato:
          type: integer
          format: int32
      example:
        id_infortunato: 12345678
        eta_all_accadimento_infortunato: 23